#!/usr/bin/env python

import random, math

def normalform(w):
    return w.strip().split("'")[0].lower()

def readwords():
    return open("/usr/share/dict/words", "r").readlines()

def makebylen():
    bylen = dict()
    for w in readwords():
        w = normalform(w)
        l = len(w)
        if not bylen.has_key(l):
            bylen[l] = dict()
        bylen[l][w] = 1
    return bylen

def password(words, nwords, maxwordlen):
    def format(word):
        fmtstr = "%%-%ds" % maxwordlen
        return fmtstr % word
    return ' '.join( map( format, random.sample( words, int( nwords ) ) ) )

def bits(n):
    bits = 0
    while n > 1:
        n = n/2
        bits += 1
    return bits

def passwords( bylen, bitsentropy, count ):

    maxwordlen = 30 # footnote 1 #
    words = reduce( lambda x, wordlen: x + bylen[ wordlen ].keys(), bylen.keys(), [] )
    wordbits = bits( len( words ) )
    nwords = math.ceil( float( bitsentropy ) / float( wordbits ) )

    print "Final wordlist contains %d words.  Picking %d words provides at least %f bits of entropy." \
        % ( len( words ), nwords, wordbits * nwords )

    return map( lambda ignore: password( words, nwords, maxwordlen ), xrange( 0, count ) )

if __name__ == "__main__":
    from optparse import OptionParser
    usage = """usage: %prog [options] arg1 arg2

See http://xkcd.com/936/

Basic argument is that picking 4 random common words for a password 
gives you about 44 bits of entropy, vs, say 28 bits of entropy for 
a "strong" (but patterned to be kinda memorable) random password.

xkcdpwgen uses a dictionary to generate a list of words in "normal" form, 
and generate candidate passwords as a few random dictionary words in a row.
Given the length of the word list that we're drawing from, we can then
pick enough words to satisfy given strenght criteria.

It defaults to 44 bits of entropy as per the cartoon.
"""
    parser = OptionParser(usage=usage)    

    parser.add_option("-b", "--bitsentropy", type="int", dest="bitsentropy", 
                      help="generate passwords with at least NUM bits of entropy", 
                      metavar="NUM", default=44)
    #parser.add_option("-e", "--equivalent", dest="equivalent", type="int",
    #                  help="generate passwords as strong as a string of LEN random printable ascii symbols", metavar="LEN")
    parser.add_option("-n", "--num", dest="numtogen", type="int",
                      help="number of candidate passwords to generate", 
                      metavar="NUM", default=20)

    (options, args) = parser.parse_args()

    for pw in passwords( makebylen(), options.bitsentropy, options.numtogen ):
        print pw

# Footnote 1:
#
# This just remains here as a workaround until I can get around to
# writing a more elegant replacement for the purpose it serves.
